/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Palette Cosmos Galactic (extraite des maquettes Stitch)
        background: '#0f0d18',
        surface: '#0f0d18',
        'surface-dim': '#0f0d18',
        'surface-bright': '#2d2a3d',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#14121f',
        'surface-container': '#1a1826',
        'surface-container-high': '#211d2e',
        'surface-container-highest': '#272335',
        'surface-variant': '#272335',
        'surface-tint': '#c799ff',
        // Primaire — Violet Nebula
        primary: '#c799ff',
        'primary-dim': '#bb83ff',
        'primary-fixed': '#bd87ff',
        'primary-fixed-dim': '#b374fe',
        'primary-container': '#bd87ff',
        'on-primary': '#440080',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#41007a',
        'on-primary-container': '#340064',
        'inverse-primary': '#7b3cc4',
        // Secondaire — Cyan Pulsar
        secondary: '#26fedc',
        'secondary-dim': '#00efce',
        'secondary-fixed': '#26fedc',
        'secondary-fixed-dim': '#00efce',
        'secondary-container': '#006b5b',
        'on-secondary': '#005d4f',
        'on-secondary-fixed': '#00483d',
        'on-secondary-fixed-variant': '#006859',
        'on-secondary-container': '#ddfff5',
        // Tertiaire — Or Stellaire
        tertiary: '#ffdb8f',
        'tertiary-dim': '#eabe55',
        'tertiary-fixed': '#f9cc61',
        'tertiary-fixed-dim': '#eabe55',
        'tertiary-container': '#f9cc61',
        'on-tertiary': '#664c00',
        'on-tertiary-fixed': '#443100',
        'on-tertiary-fixed-variant': '#674d00',
        'on-tertiary-container': '#5b4400',
        // Surface texte
        'on-surface': '#e9e3f5',
        'on-surface-variant': '#aea8b9',
        'on-background': '#e9e3f5',
        'inverse-surface': '#fdf8ff',
        'inverse-on-surface': '#575362',
        // Contours
        outline: '#777383',
        'outline-variant': '#494654',
        // Erreur / Rose
        error: '#ff6e84',
        'error-dim': '#d73357',
        'error-container': '#a70138',
        'on-error': '#490013',
        'on-error-container': '#ffb2b9',
      },
      fontFamily: {
        headline: ['SpaceGrotesk-Bold'],
        'headline-medium': ['SpaceGrotesk-SemiBold'],
        'headline-regular': ['SpaceGrotesk-Regular'],
        body: ['Manrope-Regular'],
        'body-medium': ['Manrope-Medium'],
        'body-light': ['Manrope-Light'],
        label: ['SpaceGrotesk-Medium'],
        cinzel: ['Cinzel-Regular'],
        'cinzel-bold': ['Cinzel-SemiBold'],
        mono: ['SpaceMono-Regular'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
